export const galleryItems = [
  {
    id: 'g1',
    title: 'School kit distribution',
    category: 'Education',
    src: '/gallery/01.svg',
    alt: 'Students receiving school kits',
    description: 'Notebook and stationery distribution drive with local teachers.',
  },
  {
    id: 'g2',
    title: 'Health camp day',
    category: 'Health',
    src: '/gallery/02.svg',
    alt: 'Health camp and checkups',
    description: 'Basic checkups and awareness sessions for families.',
  },
  {
    id: 'g3',
    title: 'Women self-help meeting',
    category: 'Livelihood',
    src: '/gallery/03.svg',
    alt: 'Community meeting',
    description: 'Skill and savings group discussion to strengthen livelihoods.',
  },
  {
    id: 'g4',
    title: 'Plantation drive',
    category: 'Environment',
    src: '/gallery/04.svg',
    alt: 'Tree plantation activity',
    description: 'Volunteer-led plantation with community participation.',
  },
  {
    id: 'g5',
    title: 'After-school mentoring',
    category: 'Education',
    src: '/gallery/05.svg',
    alt: 'Mentoring session',
    description: 'Mentoring, homework support, and career guidance.',
  },
  {
    id: 'g6',
    title: 'Hygiene awareness',
    category: 'Health',
    src: '/gallery/06.svg',
    alt: 'Awareness talk',
    description: 'Workshops on hygiene, nutrition, and preventive care.',
  },
  {
    id: 'g7',
    title: 'Skill training workshop',
    category: 'Livelihood',
    src: '/gallery/07.svg',
    alt: 'Skills training workshop',
    description: 'Hands-on training sessions with local trainers.',
  },
  {
    id: 'g8',
    title: 'Clean-up drive',
    category: 'Environment',
    src: '/gallery/08.svg',
    alt: 'Community clean-up',
    description: 'Neighborhood clean-up drive with volunteers.',
  },
] as const
